train_dataset_config: configs/train_txt/train_dataset_txt.txt
suffix: ''

test_lq_dir: preset/datasets/RealSR/test_LR
test_gt_dir: preset/datasets/RealSR/test_HR
test_upscale: 4

infer_steps: 1
resolution: 512
train_batch_size: 32
gradient_accumulation_steps: 1
dataloader_num_workers: 16

# Model configuration

patch_size: 2
mlp_ratio: 4
use_qknorm: True
use_swiglu: True
use_rope: True
use_rmsnorm: True
wo_shift: False

dim: 1024
depth: 28
num_heads: 16

use_8bit_adam: False


ae_type: sd2
ae_path: preset/ckpts/stable-diffusion-2-1-base
lwdecoder_path: preset/ckpts/sd21_lwdecoder.pth


# Training configuration
learning_rate: 2.0e-5
max_train_steps: 100001
checkpointing_steps: 5000
inference_steps: 5000
adam_beta1: 0.9
adam_beta2: 0.95
adam_weight_decay: 1.0e-2
adam_epsilon: 1.0e-08
max_grad_norm: 1.0
lr_scheduler: constant_with_warmup 
lr_warmup_steps: 0
lr_num_cycles: 1

use_ema: True
mixed_precision: bf16
tracker_project_name: vosr
seed: 42
ema_decay: 0.9999

time_dist: ['uniform', 0, 1.0]



cfg_ratio: 0.1
cfg_scale: 0.5

teacher_ckpt: preset/ckpts/VOSR_0.5B_ms/checkpoints/ema_model.safetensors



weak_cond_strength_aelq: 0.1
weak_cond_strength_aelq_list: [0.05, 0.25]



cond_strength_aelq_list: [5, 1]


dinov2_size: 448
enc_type: dinov2b
enc_dim: 768
layer_dinov2b_list: [8] # [2,5,8,11]

interp_type: lin

u_weight: 1.0
a: 1.0
b: 1.0

use_pos: False
train_steps: 2
encdim_ratio: 3
t_start: 0
t_end: 1
resume_ckpt: ~
pretrained_ckpt: preset/ckpts/VOSR_0.5B_ms/checkpoints/ema_model.safetensors
distill_type: rcgm # shortcut, rcgm

# logging
logging_dir: logs
output_dir: exp_vosr/
report_to: none




dataset_type: 'webdataset' # txt, webdataset
shuffle_buffer: 2000
